# Generated by Django 4.2.19 on 2025-03-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_alumni_email_alumni_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
