# Generated by Django 4.2.19 on 2025-03-16 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0004_alter_alumni_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='email',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='password',
        ),
    ]
