# Generated by Django 4.2.19 on 2025-03-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0007_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
